[
	uuid(8E069232-C779-4C11-9442-BBD988DA7900),
	version(1.0),
	helpstring("ComplexComObjectTLB")
]
library ComplexComObjectTLB
{
	importlib("STDOLE2.TLB");

	// Forward declare all types defined in this typelib
	interface IComplexComObject;
	interface IResult;

	[
		odl,
		uuid(64D7BF36-CB33-4137-9EDA-23C0AC49FED7),
		dual,
		oleautomation,
		nonextensible,
		helpstring("IComplexComObject"),
		object
	]
	interface IComplexComObject : IDispatch
	{
		[
			id(1),
			helpstring("Addition")
		]
		HRESULT Addition(
			[in] double firstValue,
			[in] double secondValue,
			[out, retval] IResult** ReturnVal);

		[
			id(2),
			helpstring("HelloWorld")
		]
		HRESULT HelloWorld(
			[out, retval] BSTR* ReturnVal);
	};

	[
		uuid(6CE0CB27-9189-4B2A-9F0A-04CEEBB5CC43),
		helpstring("ComplexComObject")
	]
	coclass ComplexComObject
	{
		[default] interface IComplexComObject;
	};

	[
		odl,
		uuid(949298B1-947B-440C-AD01-75C7D0D10334),
		dual,
		oleautomation,
		nonextensible,
		helpstring("IResult"),
		object
	]
	interface IResult : IDispatch
	{
		[
			id(1),
			helpstring("ReturnResult")
		]
		HRESULT ReturnResult(
			[out, retval] double* ReturnVal);
	};

	[
		uuid(4193FE51-B851-4267-A817-54725BA29954),
		helpstring("Result")
	]
	coclass Result
	{
		[default] interface IResult;
	};
}